<?php

namespace Database\Seeders;

use App\Enums\UserRole;
use App\Enums\MainPlatform;
use App\Models\User;
use App\Models\InfluencerProfile;
use App\Models\EnterpriseProfile;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Create Standard Users (4)
        User::factory(4)->create([
            'role' => UserRole::User,
            'password' => Hash::make('password'),
        ]);

        // 2. Create Influencers (4)
        User::factory(4)->create([
            'role' => UserRole::Influencer,
            'main_platform' => MainPlatform::Tiktok,
            'password' => Hash::make('password'),
        ])->each(function (User $user) {
            InfluencerProfile::factory()->create([
                'user_id' => $user->id,
                'first_name' => $user->first_name,
                'last_name' => $user->last_name,
                'email' => $user->email,
                'main_platform' => $user->main_platform,
                'profile_url' => $user->profile_url,
                // pseudo and niche will be generated by the factory
            ]);
        });

        // 3. Create Enterprises (4)
        User::factory(4)->create([
            'role' => UserRole::Enterprise,
            'password' => Hash::make('password'),
        ])->each(function (User $user) {
            EnterpriseProfile::factory()->create([
                'user_id' => $user->id,
            ]);
        });

        // 4. Ensure Admin exists
        if (!User::where('role', UserRole::Admin)->exists()) {
            User::factory()->create([
                'first_name' => 'Admin',
                'last_name' => 'KpiHub',
                'name' => 'Admin KpiHub',
                'email' => 'admin@kpihub.test',
                'password' => Hash::make('password'), // Set to 'password' as requested
                'role' => UserRole::Admin,
            ]);
        }
    }
}
